"""add description to customer_default_rows

Revision ID: 3d4e63fc5113
Revises: ea05bc8e3616
Create Date: 2026-04-13 23:28:48.373565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4e63fc5113'
down_revision = 'ea05bc8e3616'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('customer_default_rows', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('description', sa.Text(), nullable=False, server_default='')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_default_rows', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
