"""add price letter history table

Revision ID: 4eb178b21055
Revises: 
Create Date: 2026-03-31 02:44:46.259199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb178b21055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_letter_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('month_key', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_by_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sales_person_name', sa.String(length=255), nullable=False),
    sa.Column('sales_person_phone', sa.String(length=50), nullable=False),
    sa.Column('sales_person_email', sa.String(length=255), nullable=False),
    sa.Column('quote_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_letter_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_letter_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_letter_history_created_by_email'), ['created_by_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_letter_history_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_letter_history_month_key'), ['month_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_letter_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_letter_history_month_key'))
        batch_op.drop_index(batch_op.f('ix_price_letter_history_customer_id'))
        batch_op.drop_index(batch_op.f('ix_price_letter_history_created_by_email'))
        batch_op.drop_index(batch_op.f('ix_price_letter_history_created_at'))

    op.drop_table('price_letter_history')
    # ### end Alembic commands ###
