"""add customer locations

Revision ID: 684d334b8d5f
Revises: 3d4e63fc5113
Create Date: 2026-04-28 12:41:52.463153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d334b8d5f'
down_revision = '3d4e63fc5113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_locations_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_locations_customer_id'))

    op.drop_table('customer_locations')
    # ### end Alembic commands ###
