"""add product_id and pricing_id

Revision ID: 68866ed63c5a
Revises: ba29fee3f53e
Create Date: 2026-07-08 14:50:57.520805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68866ed63c5a'
down_revision = 'ba29fee3f53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_company_products_pricing_id'), ['pricing_id'], unique=False)

    with op.batch_alter_table('customer_default_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_default_rows_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_default_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_default_rows_product_id'))
        batch_op.drop_column('product_id')

    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_products_pricing_id'))
        batch_op.drop_column('pricing_id')

    # ### end Alembic commands ###
