"""add default_price to company_products

Revision ID: 9c6fe96d03ef
Revises: 68866ed63c5a
Create Date: 2026-07-14 14:07:07.383517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6fe96d03ef'
down_revision = '68866ed63c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    # ### end Alembic commands ###
