"""add product description

Revision ID: ea05bc8e3616
Revises: 4eb178b21055
Create Date: 2026-04-02 13:03:56.392618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea05bc8e3616'
down_revision = '4eb178b21055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_products', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
